"""Author add3

Revision ID: 17296ed35e45
Revises: 8c66a4aa96f7
Create Date: 2023-03-01 07:21:38.448079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17296ed35e45'
down_revision = '8c66a4aa96f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
