"""First

Revision ID: 5e9775abe164
Revises: 
Create Date: 2023-02-19 20:44:14.203938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9775abe164'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snowboarder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snowboarder',
    sa.Column('equip_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.CheckConstraint("size::text = ANY (ARRAY['XS'::character varying, 'S'::character varying, 'M'::character varying, 'L'::character varying, 'XL'::character varying, 'XXL'::character varying]::text[])", name='snowboarder_size_check'),
    sa.PrimaryKeyConstraint('equip_id', name='snowboarder_pkey')
    )
    # ### end Alembic commands ###
